## Numpy的核心array对象以及创建array的方法

#### array对象的背景：
* Numpy的核心数据结构，就叫做array就是数组，array对象可以是一维数组，也可以是多维数组；
* Python的List也可以实现相同的功能，但是array比List的优点在于性能好、包含数组元数据信息、大量的便捷函数；
* Numpy成为事实上的Scipy、Pandas、Scikit-Learn、Tensorflow、PaddlePaddle等框架的“通用底层语言”
* Numpy的array和Python的List的一个区别，是它元素必须都是同一种数据类型，比如都是数字int类型，这也是Numpy高性能的一个原因；

#### array本身的属性
* shape：返回一个元组，表示array的维度
* ndim：一个数字，表示array的维度的数目
* size：一个数字，表示array中所有数据元素的数目
* dtype：array中元素的数据类型

#### 创建array的方法
* 从Python的列表List和嵌套列表创建array
* 使用预定函数arange、ones/ones_like、zeros/zeros_like、empty/empty_like、full/full_like、eye等函数创建
* 生成随机数的np.random模块构建

#### array本身支持的大量操作和函数
* 直接逐元素的加减乘除等算数操作
* 更好用的面向多维的数组索引
* 求sum/mean等聚合函数
* 线性代数函数，比如求解逆矩阵、求解方程组

### 1. 使用Python的List和嵌套List创建一维的array和二维的array

In [109]:
#导入包模块
import numpy as np

In [110]:
lists = [1,2,3,4,5,6,7,8]
lists

[1, 2, 3, 4, 5, 6, 7, 8]

In [111]:
# 创建一个一维数组，也就是Python的单元素List
x = np.array([1,2,3,4,5,6,7,8])

In [112]:
x

array([1, 2, 3, 4, 5, 6, 7, 8])

In [113]:
# 创建一个二维数组，也就是Python的嵌套List
X = np.array(
    [
        [1,2,3,4],
        [5,6,7,8]
    ]
)

In [114]:
X

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### 2. 探索数组array的属性

In [115]:
x.shape

(8,)

In [116]:
X.shape #括号里数字个数代表该数组的维数
        #对于二维数组，第一个数代表行，第二个数代表列
        #对于三维数组，(x,y,z)可以解读为：三维数组里有x个y行z列的二维数组
        #依次类推

(2, 4)

In [117]:
x.ndim

1

In [118]:
X.ndim

2

In [119]:
x.size #数组中元素的个数

8

In [120]:
X.size

8

In [121]:
np.size(X,0) #axis=0,按照行的方式，如果axis=1是按照列的方式

2

In [122]:
X.shape[0]

2

In [123]:
X.shape[1]

4

In [124]:
np.size(X,1)

4

In [125]:
x.dtype

dtype('int32')

In [126]:
X.dtype

dtype('int32')

### 3. 创建array的便捷函数

#### 使用arange创建数字序列

arange([start,] stop[, step,], dtype=None)

In [127]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [128]:
np.arange(10,dtype=np.float64) #创建浮点数

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [129]:
np.arange(2, 10, 2)

array([2, 4, 6, 8])

In [130]:
np.arange(2, 5, 0.2)

array([2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4,
       4.6, 4.8])

#### 使用ones创建全是1的数组

np.ones(shape, dtype=None, order='C')

shape : int or tuple of ints
Shape of the new array, e.g., ``(2, 3)`` or ``2``.

In [131]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [132]:
np.ones(10).dtype

dtype('float64')

In [133]:
np.ones(10,dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [134]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

#### 使用ones_like创建形状相同的数组

ones_like(a, dtype=float, order='C')

In [135]:
np.ones_like(x)

array([1, 1, 1, 1, 1, 1, 1, 1])

In [136]:
np.ones_like(X)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

#### 使用zeros创建全是0的数组
np.zeros(shape, dtype=None, order='C')

In [137]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [138]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

#### 使用zeros_like创建形状相同的数组¶
np.zeros_like(a, dtype=None)

In [139]:
np.zeros_like(x)

array([0, 0, 0, 0, 0, 0, 0, 0])

In [140]:
np.zeros_like(X)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

#### 使用empty创建的数据是随机未初始化的数组
empty(shape, dtype=float, order='C')   
注意：数据是未初始化的，里面的值可能是随机值不要用

In [141]:
np.empty(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [142]:
np.empty((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

#### 使用empty_like创建形状相同的数组¶
empty_like(prototype, dtype=None)

In [143]:
np.empty_like(x)

array([6357102, 7274595, 6553710, 3342433, 4390971, 6029370, 7536725,
       7471205])

In [144]:
np.empty_like(X)

array([[7209057, 6488161, 7209071, 6357092],
       [6029363, 6881356, 7471202, 7471201]])

#### 使用full创建指定值的数组
np.full(shape, fill_value, dtype=None, order='C')

In [145]:
np.full(10, 666)

array([666, 666, 666, 666, 666, 666, 666, 666, 666, 666])

In [146]:
np.full((2,4), 333)

array([[333, 333, 333, 333],
       [333, 333, 333, 333]])

#### 使用full_like创建形状相同的数组¶
np.full_like(a, fill_value, dtype=None)

In [147]:
np.full_like(x, 666)

array([666, 666, 666, 666, 666, 666, 666, 666])

In [148]:
np.full_like(X, 666)

array([[666, 666, 666, 666],
       [666, 666, 666, 666]])

#### 使用random模块生成随机数的数组

randn(d0, d1, ..., dn)
numpy中有一些常用的用来产生随机数的函数，randn()和rand()就属于这其中。 
numpy.random.randn(d0, d1, …, dn)是从标准正态分布中返回一个或多个样本值。 
numpy.random.rand(d0, d1, …, dn)的随机样本位于[0, 1)中

In [149]:
np.random.randn()

0.6545535186606937

In [150]:
np.random.randn(3)

array([ 1.58202947, -0.425199  ,  0.12345805])

In [151]:
np.random.randn(3, 2)

array([[ 0.09382804, -1.0851217 ],
       [ 0.90281327,  0.68936376],
       [ 1.23793398, -0.12087179]])

In [152]:
np.random.randn(3, 2, 4) #batch，每个batch多少行，多少列

array([[[ 2.1233441 ,  1.13439647,  0.95132529,  0.57024832],
        [-0.62873545, -0.42007442, -0.28270994, -0.22173512]],

       [[-1.02685256,  0.74480265,  0.61966225,  1.61289144],
        [-0.29750278,  0.55076435, -0.0291409 ,  0.52722484]],

       [[-0.78302066,  0.55843276,  1.20796886, -0.92063034],
        [ 0.72908143,  0.34983935, -1.06100916,  2.02938738]]])

### 4. array本身支持的大量操作和函数

这些操作如果用Python实现需要写很多for循环，用numpy数组很容易

In [153]:
A = np.arange(10).reshape(2,5)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [154]:
A.shape

(2, 5)

In [155]:
np.shape(A)

(2, 5)

In [156]:
A+1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [157]:
A*3

array([[ 0,  3,  6,  9, 12],
       [15, 18, 21, 24, 27]])

In [158]:
np.sin(A)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849]])

In [159]:
np.exp(A) #e的x次方

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
        5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
        8.10308393e+03]])

In [160]:
B = np.random.randn(2,5)
B

array([[-0.2749836 , -0.8265458 , -0.65292797,  0.27943536, -0.43604836],
       [-0.4431373 , -1.4645088 , -0.80721694,  0.06560701,  0.90112559]])

In [161]:
A+B

array([[-0.2749836 ,  0.1734542 ,  1.34707203,  3.27943536,  3.56395164],
       [ 4.5568627 ,  4.5354912 ,  6.19278306,  8.06560701,  9.90112559]])

In [162]:
A-B

array([[0.2749836 , 1.8265458 , 2.65292797, 2.72056464, 4.43604836],
       [5.4431373 , 7.4645088 , 7.80721694, 7.93439299, 8.09887441]])