## Numpy非常有用的数组合并操作

背景：在给机器学习准备数据的过程中，经常需要进行不同来源的数据合并的操作。

以下操作均可以实现数组合并：
* np.concatenate(array_list, axis=0/1）：沿着指定axis进行数组的合并
* np.vstack或者np.row_stack(array_list)：垂直vertically、按行row wise进行数据合并
* np.hstack或者np.column_stack(array_list)：水平horizontally、按列column wise进行数据合并

In [1]:
import numpy as np

### 1. 怎样按行合并数据

实例：已经有了一组样本数据，新来了一条或者一组样本数据，怎样合并？

### 1. np.concatenate

In [2]:
a = np.arange(6).reshape(2,3)
b = np.random.randint(10,20,size=(2,3))

In [3]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [4]:
b

array([[14, 13, 16],
       [11, 17, 15]])

In [5]:
np.concatenate([a,b])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [14, 13, 16],
       [11, 17, 15]])

In [6]:
np.concatenate([a,b], axis=1)

array([[ 0,  1,  2, 14, 13, 16],
       [ 3,  4,  5, 11, 17, 15]])

### 2. np.vstack或者np.row_stack

In [7]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [8]:
b

array([[14, 13, 16],
       [11, 17, 15]])

#### np.vstack

In [9]:
np.vstack([a,b])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [14, 13, 16],
       [11, 17, 15]])

#### np.row_stack

In [10]:
np.row_stack([a,b])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [14, 13, 16],
       [11, 17, 15]])

### 3. np.hstack或者np.column_stack

In [11]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [12]:
b

array([[14, 13, 16],
       [11, 17, 15]])

#### np.hstack

In [13]:
np.hstack([a,b])

array([[ 0,  1,  2, 14, 13, 16],
       [ 3,  4,  5, 11, 17, 15]])

#### np.column_stack

In [14]:
np.column_stack([a,b])

array([[ 0,  1,  2, 14, 13, 16],
       [ 3,  4,  5, 11, 17, 15]])

In [15]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
np.stack((a,b))
#np.stack((a, b)).shape

array([[1, 2, 3],
       [2, 3, 4]])